# Generated by Django 5.0.4 on 2024-04-24 15:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onaxmain', '0002_alter_portfoliosubcategory_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfoliosubcategory',
            name='category_id',
            field=models.ForeignKey(db_column='category_id', on_delete=django.db.models.deletion.RESTRICT, related_name='fkey_sub_categories', to='onaxmain.portfoliocategory'),
        ),
    ]
