# Generated by Django 5.0.4 on 2024-04-28 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onaxmain', '0004_alter_portfoliocategory_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactOptions',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('option_name', models.CharField(max_length=100)),
                ('option_value', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'ContactOptions',
            },
        ),
    ]
