# Generated by Django 5.0.4 on 2024-04-24 15:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioCategory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('category_title', models.CharField(max_length=100)),
                ('description', models.TextField(null=True)),
                ('created_by', models.CharField(default='system', max_length=100)),
                ('updated_by', models.CharField(default='system', max_length=100)),
                ('isActive', models.BooleanField(default=True)),
                ('isDeleted', models.BooleanField(default=False)),
                ('image_path', models.CharField(max_length=250, null=True)),
                ('url_path', models.CharField(max_length=250, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'PortfolioCategory',
            },
        ),
        migrations.CreateModel(
            name='PortfolioSubCategory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sub_category_title', models.CharField(max_length=100)),
                ('description', models.TextField(null=True)),
                ('created_by', models.CharField(default='system', max_length=100)),
                ('updated_by', models.CharField(default='system', max_length=100)),
                ('isActive', models.BooleanField(default=True)),
                ('isDeleted', models.BooleanField(default=False)),
                ('image_path', models.CharField(max_length=250, null=True)),
                ('url_path', models.CharField(max_length=250, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_last_updated', models.DateTimeField(auto_now=True)),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='fkey_sub_categories', to='onaxmain.portfoliocategory')),
            ],
            options={
                'db_table': 'Portfolio_subCategory',
            },
        ),
    ]
