# Generated by Django 5.0.4 on 2024-04-25 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onaxmain', '0003_alter_portfoliosubcategory_category_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfoliocategory',
            name='description',
            field=models.TextField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='portfoliosubcategory',
            name='description',
            field=models.TextField(max_length=250, null=True),
        ),
    ]
