# Generated by Django 5.0.4 on 2024-05-12 23:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onaxmain', '0006_messages'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessages',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('phone', models.CharField(max_length=15, null=True)),
                ('message', models.TextField(max_length=500)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contact_option', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='onaxmain.contactoptions')),
            ],
            options={
                'db_table': 'ContactMessage',
            },
        ),
        migrations.DeleteModel(
            name='Messages',
        ),
    ]
